### ISSUE TITLE
TypeError: Cannot read property 'room' of undefined

### ISSUE THREAD

**Issue by simdie** [bradtraversy/chatcord#38]
There is an issue with sudden stoppage and disappearing of chat messages during users chatting.
It can only get to normal once browser is refreshed.

Here is the error code:

TypeError: Cannot read property 'room' of undefined
    at Socket.socket.on.msg (/home/firszmuu/beyok.firstcla.net/server.js:51:16)
    at Socket.emit (events.js:198:13)
    at /home/firszmuu/beyok.firstcla.net/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
/home/firszmuu/beyok.firstcla.net/server.js:51
   io.to(user.room).emit('message', formatMessage(user.username, msg));
                   ^

Kindly assist

**Comment by MihirNasit-2512** [comment]
**put this part in condition :** 

io.to(user.room).emit('roomUsers',{
          room : user.room,
          users : getRoomUsers(user.room)
        });

**After that it looks like :** 

socket.on('disconnect',()=>{
      const user = userLeave(socket.id);
      if(user){
        io.to(user.room).emit('message',formatMessage(botName,`${user.username} left the chat`));
        io.to(user.room).emit('roomUsers',{
          room : user.room,
          users : getRoomUsers(user.room)
        });
      }
    });

**Comment by Jatan88** [comment]
Have u got solution to this problem?

**Comment by tauseedzaman** [comment]
I did not get any errors, make sure you have installed everything as given in the readme file
